export default {
	STEP_NEXT: 'gameRules/STEP_NEXT',
	QUESTIONS_RESET: 'gameRules/QUESTIONS_RESET',

	ARTIST_USER_ANSWER: 'gameRules/ARTIST_USER_ANSWER',
	GENGE_USER_ANSWER: 'gameRules/GENGE_USER_ANSWER',
	GAME_TIMER: 'gameRules/GAME_TIMER',
	END_TIME: 'gameRules/END_TIME',
	GAME_RESET: 'gameRules/GAME_RESET',

};